name: Lint Application Packages

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'main'
      - 'develop'


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn
      - run: yarn lint